# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Phrygia Dvlog"
description: > # this means to ignore newlines until "email:"
   

email: dmsgp62@gmail.com
#blog logo
logo: "/assets/images/topLogo.png"
float_logo: true # true, false (default)

# blog cover
cover: "/assets/images/blogTop.jpg"

name: 'phrygia'
author: 'phrygia'
author_image: "/assets/images/author.jpg"

paginate:	5

url: "phrygia.github.io" # the base hostname & protocol for your site
baseurl: "/blog"
#used to display twitter cards
twitter_handle: ''

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
